### ISSUE TITLE
socket_set_option(): unable to set socket option [33]: Numerical argument out of domain

### ISSUE THREAD

**Issue by akromjon** [laradevsbd/zkteco-sdk-laravel#2]
After Fixing Class 'Nurkarim\Zkteco\Http\Library\ZKLib' not found issue, "socket_set_option(): unable to set socket option [33]: Numerical argument out of domain" appears

**Comment by nurkarim** [comment]
You should enable socket extension from PHP ini file
;extension=soap
;extension=sockets
To
extension=soap
extension=sockets
