### ISSUE TITLE
Class 'Nurkarim\Zkteco\Http\Library\ZKLib

### ISSUE THREAD

**Issue by primeit2030** [laradevsbd/zkteco-sdk-laravel#3]
Error

Class 'Nurkarim\Zkteco\Http\Library\ZKLib

**Comment by poldelgado** [comment]
I 've the same issue.

**Comment by nurkarim** [comment]
These issues are solved. remove old package and add again composer require
laradevsbd/zkteco-sdk

**Comment by karleo** [comment]
Hello,  
I encounter same issue . Class 'Nurkarim\Zkteco\Http\Library\ZKLib
I just delete the package and install again but i get same issue. Can you please help us

**Comment by nurkarim** [comment]
Hi, I did check. I have solved the problem. You can change  Nurkarim to
Laradevsbd
